include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # - prefer_const_constructors    
    
    - prefer_relative_imports
    - directives_ordering
    
    # - avoid_relative_lib_imports
    # - always_use_package_imports
