name: wattz
description: "An EV Charging Application"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  bloc: ^9.2.0
  cupertino_icons: ^1.0.9
  cupertino_native: ^0.1.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/charging/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/welcome/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
