name: wattz
description: "An EV Charging Application"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  adaptive_platform_ui: ^0.1.107
  bloc: ^9.2.0
  cupertino_icons: ^1.0.9
  cupertino_native: ^0.1.1
  equatable: ^2.0.8
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  introduction_screen: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/charging/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/welcome/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/ezcharge_logo.png"
  adaptive_icon_background: "#1e1e1e"
  adaptive_icon_foreground: "assets/images/logo/ezcharge_logo_foreground.png"
