List<Map<String, dynamic>> stationList = [
  {
    "id": "stn_001",
    "name": "Suria KLCC Basement Hub",
    "address": "Basement 2, Suria KLCC, Jalan Ampang, 50088 Kuala Lumpur",
    "latitude": 3.1579,
    "longitude": 101.7116,
    "status": "active",
    "chargers": [
      {
        "id": "chg_101",
        "status": "available",
        "powerOutput": 180.0,
        "sessionFee": 5.0,
        "ratePerKwh": 1.50,
        "connectorType": "ccs2",
      },
      {
        "id": "chg_102",
        "status": "charging",
        "powerOutput": 22.0,
        "sessionFee": 0.0,
        "ratePerKwh": 0.90,
        "connectorType": "type2",
      },
    ],
  },
  {
    "id": "stn_002",
    "name": "Mid Valley Megamall Zone A",
    "address":
        "P1 South Court, Mid Valley Megamall, Lingkaran Syed Putra, 59200 Kuala Lumpur",
    "latitude": 3.1168,
    "longitude": 101.6774,
    "status": "active",
    "chargers": [
      {
        "id": "chg_201",
        "status": "charging",
        "powerOutput": 50.0,
        "sessionFee": 3.0,
        "ratePerKwh": 1.20,
        "connectorType": "ccs2",
      },
      {
        "id": "chg_202",
        "status": "offline",
        "powerOutput": 50.0,
        "sessionFee": 3.0,
        "ratePerKwh": 1.20,
        "connectorType": "chademo",
      },
    ],
  },
  {
    "id": "stn_003",
    "name": "Bangsar Shopping Centre",
    "address": "Jalan Tessenfon, Bangsar, 59100 Kuala Lumpur",
    "latitude": 3.1428,
    "longitude": 101.6667,
    "status": "active",
    "chargers": [
      {
        "id": "chg_301",
        "status": "available",
        "powerOutput": 11.0,
        "sessionFee": 0.0,
        "ratePerKwh": 0.80,
        "connectorType": "type2",
      },
    ],
  },
  {
    "id": "stn_004",
    "name": "1 Utama New Wing",
    "address":
        "Lebuh Bandar Utama, Bandar Utama, 47800 Petaling Jaya, Selangor",
    "latitude": 3.1511,
    "longitude": 101.6154,
    "status": "active",
    "chargers": [
      {
        "id": "chg_401",
        "status": "available",
        "powerOutput": 350.0,
        "sessionFee": 10.0,
        "ratePerKwh": 2.20,
        "connectorType": "ccs2",
      },
      {
        "id": "chg_402",
        "status": "available",
        "powerOutput": 350.0,
        "sessionFee": 10.0,
        "ratePerKwh": 2.20,
        "connectorType": "ccs2",
      },
    ],
  },
  {
    "id": "stn_005",
    "name": "Sunway Pyramid P2",
    "address": "Jalan PJS 11/15, Bandar Sunway, 47500 Subang Jaya, Selangor",
    "latitude": 3.0731,
    "longitude": 101.6078,
    "status": "active",
    "chargers": [
      {
        "id": "chg_501",
        "status": "maintenance",
        "powerOutput": 22.0,
        "sessionFee": 0.0,
        "ratePerKwh": 1.00,
        "connectorType": "type2",
      },
    ],
  },
  {
    "id": "stn_006",
    "name": "IOI City Mall Phase 2",
    "address": "Lebuh IRC, IOI Resort City, 62502 Putrajaya",
    "latitude": 2.9704,
    "longitude": 101.7144,
    "status": "active",
    "chargers": [
      {
        "id": "chg_601",
        "status": "available",
        "powerOutput": 120.0,
        "sessionFee": 5.0,
        "ratePerKwh": 1.60,
        "connectorType": "ccs2",
      },
      {
        "id": "chg_602",
        "status": "charging",
        "powerOutput": 120.0,
        "sessionFee": 5.0,
        "ratePerKwh": 1.60,
        "connectorType": "ccs2",
      },
    ],
  },
  {
    "id": "stn_007",
    "name": "Gurney Plaza B1",
    "address": "Persiaran Gurney, 10250 George Town, Penang",
    "latitude": 5.4377,
    "longitude": 100.3097,
    "status": "active",
    "chargers": [
      {
        "id": "chg_701",
        "status": "available",
        "powerOutput": 22.0,
        "sessionFee": 0.0,
        "ratePerKwh": 0.90,
        "connectorType": "type2",
      },
    ],
  },
  {
    "id": "stn_008",
    "name": "Paradigm Mall JB",
    "address": "Jalan Skudai, 81200 Johor Bahru, Johor",
    "latitude": 1.5142,
    "longitude": 103.6849,
    "status": "active",
    "chargers": [
      {
        "id": "chg_801",
        "status": "charging",
        "powerOutput": 150.0,
        "sessionFee": 6.0,
        "ratePerKwh": 1.70,
        "connectorType": "ccs2",
      },
    ],
  },
  {
    "id": "stn_009",
    "name": "PLUS Rawang Northbound",
    "address": "KM 440.5, North-South Expressway, 48000 Rawang, Selangor",
    "latitude": 3.3221,
    "longitude": 101.5743,
    "status": "active",
    "chargers": [
      {
        "id": "chg_901",
        "status": "available",
        "powerOutput": 180.0,
        "sessionFee": 0.0,
        "ratePerKwh": 2.40,
        "connectorType": "ccs2",
      },
      {
        "id": "chg_902",
        "status": "available",
        "powerOutput": 180.0,
        "sessionFee": 0.0,
        "ratePerKwh": 2.40,
        "connectorType": "ccs2",
      },
    ],
  },
  {
    "id": "stn_010",
    "name": "Genting Highlands Premium Outlets",
    "address":
        "KM 13, Genting Highlands Resort, 69000 Genting Highlands, Pahang",
    "latitude": 3.4074,
    "longitude": 101.7677,
    "status": "maintenance",
    "chargers": [
      {
        "id": "chg_010",
        "status": "offline",
        "powerOutput": 50.0,
        "sessionFee": 5.0,
        "ratePerKwh": 1.40,
        "connectorType": "chademo",
      },
    ],
  },
];
