// List of 100 Station based on my lat lng

List<Map<String, dynamic>> stationList = [
  // Station 1
  {
    "DataProvider": {
      "WebsiteURL": "https://www.chargesini.com",
      "Comments": "OCPI with Data Sharing Agreement",
      "DataProviderStatusType": {
        "IsProviderEnabled": true,
        "ID": 20,
        "Title": "Automated Import",
      },
      "IsRestrictedEdit": true,
      "IsOpenDataLicensed": true,
      "IsApprovedImport": true,
      "License": "CC0",
      "DateLastImported": "2026-06-09T04:03:08.037Z",
      "ID": 41,
      "Title": "ChargeSini",
    },
    "OperatorInfo": null,
    "UsageType": {
      "IsPayAtLocation": false,
      "IsMembershipRequired": true,
      "IsAccessKeyRequired": true,
      "ID": 4,
      "Title": "Public - Membership Required",
    },
    "StatusType": {
      "IsOperational": true,
      "IsUserSelectable": true,
      "ID": 50,
      "Title": "Operational",
    },
    "SubmissionStatus": {
      "IsLive": true,
      "ID": 200,
      "Title": "Submission Published",
    },
    "UserComments": null,
    "PercentageSimilarity": null,
    "MediaItems": null,
    "IsRecentlyVerified": true,
    "DateLastVerified": "2026-06-09T04:03:00Z",
    "ID": 484850,
    "UUID": "C6F4E43E-410B-4C89-B466-4B49C3092D88",
    "ParentChargePointID": null,
    "DataProviderID": 41,
    "DataProvidersReference": "539",
    "OperatorID": null,
    "OperatorsReference": null,
    "UsageTypeID": 4,
    "UsageCost": null,
    "AddressInfo": {
      "ID": 485239,
      "Title": "[Restricted] FORTUNE CENTRA RESIDENCES (Residential Condo)",
      "AddressLine1": "Fortune Centra Residence",
      "AddressLine2": null,
      "Town": "Kuala Lumpur",
      "StateOrProvince": null,
      "Postcode": "52100",
      "CountryID": 137,
      "Country": {
        "ISOCode": "MY",
        "ContinentCode": "AS",
        "ID": 137,
        "Title": "Malaysia",
      },
      "Latitude": 3.215377,
      "Longitude": 101.643318,
      "ContactTelephone1": null,
      "ContactTelephone2": null,
      "ContactEmail": null,
      "AccessComments": "Indoor Visitor Parking",
      "RelatedURL": null,
      "Distance": 0.4835924369051793,
      "DistanceUnit": 1,
    },
    "Connections": [
      {
        "ID": 813300,
        "ConnectionTypeID": 1036,
        "ConnectionType": {
          "FormalName": "IEC 62196-2",
          "IsDiscontinued": false,
          "IsObsolete": false,
          "ID": 1036,
          "Title": "Type 2 (Tethered Connector) ",
        },
        "Reference": "1991",
        "StatusTypeID": 50,
        "StatusType": {
          "IsOperational": true,
          "IsUserSelectable": true,
          "ID": 50,
          "Title": "Operational",
        },
        "LevelID": 2,
        "Level": {
          "Comments": "Over 2 kW, usually non-domestic socket type",
          "IsFastChargeCapable": false,
          "ID": 2,
          "Title": "Level 2 : Medium (Over 2kW)",
        },
        "Amps": 32,
        "Voltage": 400,
        "PowerKW": 22,
        "CurrentTypeID": 20,
        "CurrentType": {
          "Description": "Alternating Current - Three Phase",
          "ID": 20,
          "Title": "AC (Three-Phase)",
        },
        "Quantity": 1,
        "Comments": null,
      },
      {
        "ID": 813301,
        "ConnectionTypeID": 1036,
        "ConnectionType": {
          "FormalName": "IEC 62196-2",
          "IsDiscontinued": false,
          "IsObsolete": false,
          "ID": 1036,
          "Title": "Type 2 (Tethered Connector) ",
        },
        "Reference": "1998",
        "StatusTypeID": 50,
        "StatusType": {
          "IsOperational": true,
          "IsUserSelectable": true,
          "ID": 50,
          "Title": "Operational",
        },
        "LevelID": 2,
        "Level": {
          "Comments": "Over 2 kW, usually non-domestic socket type",
          "IsFastChargeCapable": false,
          "ID": 2,
          "Title": "Level 2 : Medium (Over 2kW)",
        },
        "Amps": 32,
        "Voltage": 400,
        "PowerKW": 22,
        "CurrentTypeID": 20,
        "CurrentType": {
          "Description": "Alternating Current - Three Phase",
          "ID": 20,
          "Title": "AC (Three-Phase)",
        },
        "Quantity": 1,
        "Comments": null,
      },
      {
        "ID": 813302,
        "ConnectionTypeID": 33,
        "ConnectionType": {
          "FormalName": "IEC 62196-3 Configuration FF",
          "IsDiscontinued": false,
          "IsObsolete": false,
          "ID": 33,
          "Title": "CCS (Type 2)",
        },
        "Reference": "2022",
        "StatusTypeID": 50,
        "StatusType": {
          "IsOperational": true,
          "IsUserSelectable": true,
          "ID": 50,
          "Title": "Operational",
        },
        "LevelID": 3,
        "Level": {
          "Comments": "40KW and Higher",
          "IsFastChargeCapable": true,
          "ID": 3,
          "Title": "Level 3:  High (Over 40kW)",
        },
        "Amps": 62,
        "Voltage": 400,
        "PowerKW": 40,
        "CurrentTypeID": 30,
        "CurrentType": {
          "Description": "Direct Current",
          "ID": 30,
          "Title": "DC",
        },
        "Quantity": 1,
        "Comments": null,
      },
      {
        "ID": 813303,
        "ConnectionTypeID": 33,
        "ConnectionType": {
          "FormalName": "IEC 62196-3 Configuration FF",
          "IsDiscontinued": false,
          "IsObsolete": false,
          "ID": 33,
          "Title": "CCS (Type 2)",
        },
        "Reference": "2023",
        "StatusTypeID": 50,
        "StatusType": {
          "IsOperational": true,
          "IsUserSelectable": true,
          "ID": 50,
          "Title": "Operational",
        },
        "LevelID": 3,
        "Level": {
          "Comments": "40KW and Higher",
          "IsFastChargeCapable": true,
          "ID": 3,
          "Title": "Level 3:  High (Over 40kW)",
        },
        "Amps": 62,
        "Voltage": 400,
        "PowerKW": 40,
        "CurrentTypeID": 30,
        "CurrentType": {
          "Description": "Direct Current",
          "ID": 30,
          "Title": "DC",
        },
        "Quantity": 1,
        "Comments": null,
      },
    ],
    "NumberOfPoints": null,
    "GeneralComments": null,
    "DatePlanned": null,
    "DateLastConfirmed": null,
    "StatusTypeID": 50,
    "DateLastStatusUpdate": "2026-06-09T04:03:00Z",
    "MetadataValues": null,
    "DataQualityLevel": 1,
    "DateCreated": "2026-04-09T08:06:00Z",
    "SubmissionStatusTypeID": 200,
  },
  // Station 2
  {
    "DataProvider": {
      "WebsiteURL": "http://openchargemap.org",
      "Comments": null,
      "DataProviderStatusType": {
        "IsProviderEnabled": true,
        "ID": 1,
        "Title": "Manual Data Entry",
      },
      "IsRestrictedEdit": false,
      "IsOpenDataLicensed": true,
      "IsApprovedImport": true,
      "License":
          "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      "DateLastImported": null,
      "ID": 1,
      "Title": "Open Charge Map Contributors",
    },
    "OperatorInfo": {
      "WebsiteURL": "https://chargev.my/",
      "Comments": null,
      "PhonePrimaryContact": null,
      "PhoneSecondaryContact": null,
      "IsPrivateIndividual": false,
      "AddressInfo": null,
      "BookingURL": null,
      "ContactEmail": "chargev@greentechmalaysia.my",
      "FaultReportEmail": "chargev@greentechmalaysia.my",
      "IsRestrictedEdit": false,
      "ID": 3338,
      "Title": "chargEV",
    },
    "UsageType": {
      "IsPayAtLocation": false,
      "IsMembershipRequired": true,
      "IsAccessKeyRequired": true,
      "ID": 4,
      "Title": "Public - Membership Required",
    },
    "StatusType": {
      "IsOperational": true,
      "IsUserSelectable": true,
      "ID": 50,
      "Title": "Operational",
    },
    "SubmissionStatus": {
      "IsLive": true,
      "ID": 200,
      "Title": "Submission Published",
    },
    "UserComments": null,
    "PercentageSimilarity": null,
    "MediaItems": null,
    "IsRecentlyVerified": false,
    "DateLastVerified": "2021-10-17T14:52:00Z",
    "ID": 189601,
    "UUID": "8229109F-6E26-467C-B5C7-6A3183A2DA7C",
    "ParentChargePointID": null,
    "DataProviderID": 1,
    "DataProvidersReference": null,
    "OperatorID": 3338,
    "OperatorsReference": null,
    "UsageTypeID": 4,
    "UsageCost": "Yearly Subscription",
    "AddressInfo": {
      "ID": 189960,
      "Title": "Kiara Bay Sales Gallery",
      "AddressLine1": "Off Middle Ring Road 2",
      "AddressLine2": "Jln Lingkaran Tengah 2",
      "Town": "Kiara Bay",
      "StateOrProvince": "Wilayah Persekutuan Kuala Lumpur",
      "Postcode": "52000",
      "CountryID": 137,
      "Country": {
        "ISOCode": "MY",
        "ContinentCode": "AS",
        "ID": 137,
        "Title": "Malaysia",
      },
      "Latitude": 3.2255662859760434,
      "Longitude": 101.65056532499057,
      "ContactTelephone1": "+60 11 2337 3387",
      "ContactTelephone2": "1-800-88-8008",
      "ContactEmail": null,
      "AccessComments": "(3.2256881, 101.6504840)",
      "RelatedURL": "https://chargev.my/",
      "Distance": 0.9907900312062821,
      "DistanceUnit": 1,
    },
    "Connections": [
      {
        "ID": 306722,
        "ConnectionTypeID": 25,
        "ConnectionType": {
          "FormalName": "IEC 62196-2 Type 2",
          "IsDiscontinued": false,
          "IsObsolete": false,
          "ID": 25,
          "Title": "Type 2 (Socket Only)",
        },
        "Reference": null,
        "StatusTypeID": 50,
        "StatusType": {
          "IsOperational": true,
          "IsUserSelectable": true,
          "ID": 50,
          "Title": "Operational",
        },
        "LevelID": 2,
        "Level": {
          "Comments": "Over 2 kW, usually non-domestic socket type",
          "IsFastChargeCapable": false,
          "ID": 2,
          "Title": "Level 2 : Medium (Over 2kW)",
        },
        "Amps": 32,
        "Voltage": 415,
        "PowerKW": 22,
        "CurrentTypeID": 20,
        "CurrentType": {
          "Description": "Alternating Current - Three Phase",
          "ID": 20,
          "Title": "AC (Three-Phase)",
        },
        "Quantity": 2,
        "Comments": null,
      },
    ],
    "NumberOfPoints": 2,
    "GeneralComments": null,
    "DatePlanned": null,
    "DateLastConfirmed": null,
    "StatusTypeID": 50,
    "DateLastStatusUpdate": "2021-10-17T14:52:00Z",
    "MetadataValues": null,
    "DataQualityLevel": 1,
    "DateCreated": "2021-10-17T02:27:00Z",
    "SubmissionStatusTypeID": 200,
  },
];
